development:
  adapter: mysql2
  database: shiftthesubsidies_development
  username: diligent_rordb 
  password: d1l1g3nt!
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2 
  database: shiftthesubsidies_production
  username: diligent_rordb
  password: d1l1g3nt!
  host: localhost